-- Postgres schema for xray-log-analyzer.
--
-- Ported from SQLite migrate() in storage.go. This file is idempotent
-- (CREATE TABLE IF NOT EXISTS / CREATE INDEX IF NOT EXISTS) and is applied
-- on startup. Boolean-like columns (resolved, sent, is_connected, etc.) are
-- kept as INTEGER for wire compatibility with the existing Go code paths
-- (`WHERE resolved = 0`, `WHERE sent = 1`, etc.); Task 5 may tighten them
-- to BOOLEAN once the query layer is migrated.
--
-- Translation rules applied:
--   INTEGER PRIMARY KEY AUTOINCREMENT -> BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY
--   DATETIME DEFAULT CURRENT_TIMESTAMP -> TIMESTAMPTZ DEFAULT NOW()
--   DATETIME (nullable/other) -> TIMESTAMPTZ
--   REAL -> DOUBLE PRECISION
--   INSERT OR IGNORE -> INSERT ... ON CONFLICT DO NOTHING
--   INTEGER for counters/sizes -> BIGINT
--   INTEGER for small bounded values (confidence 0-100, risk_score, etc.) -> INTEGER
--
-- Historical ALTER TABLE migrations from storage.go have been folded into the
-- CREATE TABLE definitions since this is a fresh schema.

-- =============================================================================
-- Node and user traffic stats
-- =============================================================================

CREATE TABLE IF NOT EXISTS node_stats (
    node_id          TEXT PRIMARY KEY,
    total_requests   BIGINT DEFAULT 0,
    blacklist_hits   BIGINT DEFAULT 0,
    unique_users     BIGINT DEFAULT 0,
    last_seen        TIMESTAMPTZ,
    last_batch_time  TIMESTAMPTZ,
    last_batch_count BIGINT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS user_stats (
    id                    BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    node_id               TEXT NOT NULL,
    user_email            TEXT NOT NULL,
    total_requests        BIGINT DEFAULT 0,
    blacklist_hits        BIGINT DEFAULT 0,
    unique_destinations   BIGINT DEFAULT 0,
    last_seen             TIMESTAMPTZ,
    last_ip               TEXT,
    last_blacklist_hit    TIMESTAMPTZ,
    last_blacklist_domain TEXT,
    UNIQUE (node_id, user_email)
);

CREATE TABLE IF NOT EXISTS blacklist_matches (
    id           BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    node_id      TEXT NOT NULL,
    user_email   TEXT NOT NULL,
    source_ip    TEXT NOT NULL,
    destination  TEXT NOT NULL,
    matched_rule TEXT NOT NULL,
    timestamp    TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS alerts (
    id          BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    type        TEXT NOT NULL,
    node_id     TEXT NOT NULL,
    user_email  TEXT NOT NULL,
    source_ip   TEXT,
    destination TEXT,
    count       BIGINT DEFAULT 0,
    message     TEXT NOT NULL,
    created_at  TIMESTAMPTZ DEFAULT NOW(),
    sent        INTEGER DEFAULT 0 NOT NULL
);

CREATE TABLE IF NOT EXISTS hourly_stats (
    id             BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    node_id        TEXT NOT NULL,
    hour           TIMESTAMPTZ NOT NULL,
    total_requests BIGINT DEFAULT 0,
    blacklist_hits BIGINT DEFAULT 0,
    unique_users   BIGINT DEFAULT 0,
    UNIQUE (node_id, hour)
);

CREATE TABLE IF NOT EXISTS user_destinations (
    id            BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_email    TEXT NOT NULL,
    node_id       TEXT NOT NULL,
    destination   TEXT NOT NULL,
    request_count BIGINT DEFAULT 1,
    first_seen    TIMESTAMPTZ,
    last_seen     TIMESTAMPTZ,
    UNIQUE (user_email, node_id, destination)
);

-- =============================================================================
-- Threat matches and aggregated threat stats
-- =============================================================================

CREATE TABLE IF NOT EXISTS threat_matches (
    id          BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_email  TEXT NOT NULL,
    node_id     TEXT NOT NULL,
    source_ip   TEXT NOT NULL,
    destination TEXT NOT NULL,
    threat_type TEXT NOT NULL,
    source      TEXT NOT NULL,
    confidence  INTEGER DEFAULT 0,
    description TEXT,
    matched_at  TIMESTAMPTZ DEFAULT NOW()
);

-- Singleton row: total threat match counter
CREATE TABLE IF NOT EXISTS threat_stats_agg (
    id            INTEGER PRIMARY KEY CHECK (id = 1),
    total_matches BIGINT DEFAULT 0,
    last_updated  TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS threat_type_stats (
    threat_type TEXT PRIMARY KEY,
    match_count BIGINT DEFAULT 0,
    last_match  TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS user_threat_stats (
    user_email  TEXT NOT NULL,
    threat_type TEXT NOT NULL,
    match_count BIGINT DEFAULT 0,
    last_match  TIMESTAMPTZ,
    PRIMARY KEY (user_email, threat_type)
);

CREATE TABLE IF NOT EXISTS user_threat_domains (
    user_email  TEXT NOT NULL,
    threat_type TEXT NOT NULL,
    domain      TEXT NOT NULL,
    hit_count   BIGINT DEFAULT 1,
    last_seen   TIMESTAMPTZ DEFAULT NOW(),
    PRIMARY KEY (user_email, threat_type, domain)
);

CREATE TABLE IF NOT EXISTS threat_hourly_stats (
    hour         TEXT NOT NULL,            -- YYYY-MM-DDTHH
    threat_type  TEXT NOT NULL,
    match_count  BIGINT DEFAULT 0,
    unique_users BIGINT DEFAULT 0,
    PRIMARY KEY (hour, threat_type)
);

CREATE TABLE IF NOT EXISTS threat_hourly_users (
    hour        TEXT NOT NULL,
    threat_type TEXT NOT NULL,
    user_email  TEXT NOT NULL,
    PRIMARY KEY (hour, threat_type, user_email)
);

CREATE TABLE IF NOT EXISTS threat_daily_stats (
    day          TEXT NOT NULL,            -- YYYY-MM-DD
    threat_type  TEXT NOT NULL,
    match_count  BIGINT DEFAULT 0,
    unique_users BIGINT DEFAULT 0,
    PRIMARY KEY (day, threat_type)
);

CREATE TABLE IF NOT EXISTS threat_daily_users (
    day         TEXT NOT NULL,
    threat_type TEXT NOT NULL,
    user_email  TEXT NOT NULL,
    PRIMARY KEY (day, threat_type, user_email)
);

CREATE TABLE IF NOT EXISTS threat_geo_stats (
    country_code TEXT NOT NULL,
    country_name TEXT NOT NULL,
    threat_type  TEXT NOT NULL,
    match_count  BIGINT DEFAULT 0,
    unique_users BIGINT DEFAULT 0,
    last_match   TIMESTAMPTZ,
    PRIMARY KEY (country_code, threat_type)
);

-- =============================================================================
-- GeoIP / user locations / IP history
-- =============================================================================

CREATE TABLE IF NOT EXISTS user_locations (
    user_email    TEXT NOT NULL,
    country_code  TEXT NOT NULL,
    country_name  TEXT NOT NULL,
    city          TEXT,
    latitude      DOUBLE PRECISION,
    longitude     DOUBLE PRECISION,
    last_seen     TIMESTAMPTZ DEFAULT NOW(),
    request_count BIGINT DEFAULT 1,
    PRIMARY KEY (user_email, country_code)
);

CREATE TABLE IF NOT EXISTS user_ip_history (
    id            BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_email    TEXT NOT NULL,
    ip_address    TEXT NOT NULL,
    node_id       TEXT,
    country_code  TEXT,
    country_name  TEXT,
    city          TEXT,
    latitude      DOUBLE PRECISION,
    longitude     DOUBLE PRECISION,
    first_seen    TIMESTAMPTZ DEFAULT NOW(),
    last_seen     TIMESTAMPTZ DEFAULT NOW(),
    request_count BIGINT DEFAULT 1,
    UNIQUE (user_email, ip_address)
);

-- =============================================================================
-- Anomaly detection / user risk profiles
-- =============================================================================

CREATE TABLE IF NOT EXISTS anomalies (
    id          TEXT PRIMARY KEY,
    type        TEXT NOT NULL,
    severity    TEXT NOT NULL,
    user_email  TEXT,
    description TEXT NOT NULL,
    details     TEXT,                      -- JSON encoded
    detected_at TIMESTAMPTZ DEFAULT NOW(),
    resolved    INTEGER DEFAULT 0 NOT NULL
);

CREATE TABLE IF NOT EXISTS user_activity_baseline (
    user_email         TEXT PRIMARY KEY,
    avg_daily_requests DOUBLE PRECISION DEFAULT 0,
    avg_daily_threats  DOUBLE PRECISION DEFAULT 0,
    typical_hours      TEXT,               -- JSON array
    typical_countries  TEXT,               -- JSON array
    first_seen         TIMESTAMPTZ,
    updated_at         TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS user_risk_profiles (
    user_email       TEXT PRIMARY KEY,
    risk_level       TEXT NOT NULL DEFAULT 'low',
    risk_score       INTEGER NOT NULL DEFAULT 0,
    total_matches    BIGINT DEFAULT 0,
    threats_by_type  TEXT,                 -- JSON map
    unique_countries INTEGER DEFAULT 0,
    anomaly_count    INTEGER DEFAULT 0,
    first_seen       TIMESTAMPTZ,
    last_activity    TIMESTAMPTZ,
    days_active      INTEGER DEFAULT 0,
    top_domains      TEXT,                 -- JSON array
    risk_factors     TEXT,                 -- JSON array
    trend_direction  TEXT DEFAULT 'stable',
    updated_at       TIMESTAMPTZ DEFAULT NOW()
);

-- =============================================================================
-- DNS analysis
-- =============================================================================

CREATE TABLE IF NOT EXISTS dns_domain_stats (
    domain         TEXT PRIMARY KEY,
    total_hits     BIGINT DEFAULT 0,
    unique_users   BIGINT DEFAULT 0,
    threat_types   TEXT,                   -- JSON array
    sources        TEXT,                   -- JSON array
    first_seen     TIMESTAMPTZ,
    last_seen      TIMESTAMPTZ,
    risk_level     TEXT DEFAULT 'low',
    category_hits  TEXT                    -- JSON map category -> count
);

CREATE TABLE IF NOT EXISTS dns_hourly_stats (
    hour            TEXT PRIMARY KEY,      -- 2006-01-02T15
    total_queries   BIGINT DEFAULT 0,
    blocked_queries BIGINT DEFAULT 0,
    unique_users    BIGINT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS dns_daily_stats (
    day             TEXT PRIMARY KEY,      -- 2006-01-02
    total_queries   BIGINT DEFAULT 0,
    blocked_queries BIGINT DEFAULT 0,
    unique_users    BIGINT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS user_dns_stats (
    user_email      TEXT PRIMARY KEY,
    total_queries   BIGINT DEFAULT 0,
    blocked_queries BIGINT DEFAULT 0,
    top_domains     TEXT,                  -- JSON array
    updated_at      TIMESTAMPTZ DEFAULT NOW()
);

-- =============================================================================
-- Reports
-- =============================================================================

CREATE TABLE IF NOT EXISTS reports (
    id             TEXT PRIMARY KEY,
    type           TEXT NOT NULL,
    format         TEXT NOT NULL,
    title          TEXT NOT NULL,
    description    TEXT,
    start_date     TIMESTAMPTZ,
    end_date       TIMESTAMPTZ,
    generated_at   TIMESTAMPTZ DEFAULT NOW(),
    status         TEXT DEFAULT 'pending',
    sections       TEXT,                   -- JSON array
    top_threats    TEXT,                   -- JSON array
    top_users      TEXT,                   -- JSON array
    top_countries  TEXT,                   -- JSON array
    summary        TEXT                    -- JSON object
);

-- =============================================================================
-- User correlation tables for AI analysis
-- =============================================================================

CREATE TABLE IF NOT EXISTS ip_user_map (
    ip_address    TEXT NOT NULL,
    user_email    TEXT NOT NULL,
    node_id       TEXT,
    first_seen    TIMESTAMPTZ DEFAULT NOW(),
    last_seen     TIMESTAMPTZ DEFAULT NOW(),
    request_count BIGINT DEFAULT 1,
    PRIMARY KEY (ip_address, user_email)
);

CREATE TABLE IF NOT EXISTS hwid_user_map (
    hwid          TEXT NOT NULL,
    user_email    TEXT NOT NULL,
    platform      TEXT,
    first_seen    TIMESTAMPTZ DEFAULT NOW(),
    last_seen     TIMESTAMPTZ DEFAULT NOW(),
    request_count BIGINT DEFAULT 1,
    PRIMARY KEY (hwid, user_email)
);

CREATE TABLE IF NOT EXISTS user_fingerprints (
    id            BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_email    TEXT NOT NULL,
    ip_address    TEXT NOT NULL,
    hwid          TEXT,
    user_agent    TEXT,
    node_id       TEXT,
    first_seen    TIMESTAMPTZ DEFAULT NOW(),
    last_seen     TIMESTAMPTZ DEFAULT NOW(),
    session_count BIGINT DEFAULT 1,
    UNIQUE (user_email, ip_address, hwid)
);

CREATE TABLE IF NOT EXISTS user_clusters (
    cluster_id    TEXT NOT NULL,
    user_email    TEXT NOT NULL,
    reason        TEXT NOT NULL,           -- 'shared_ip' | 'shared_hwid' | 'both'
    shared_value  TEXT NOT NULL,
    confidence    DOUBLE PRECISION DEFAULT 0.5,
    first_linked  TIMESTAMPTZ DEFAULT NOW(),
    last_seen     TIMESTAMPTZ DEFAULT NOW(),
    PRIMARY KEY (cluster_id, user_email)
);

CREATE TABLE IF NOT EXISTS user_ai_profile (
    user_email               TEXT PRIMARY KEY,
    -- Identity
    unique_ips               BIGINT DEFAULT 0,
    unique_hwids             BIGINT DEFAULT 0,
    unique_fingerprints      BIGINT DEFAULT 0,
    unique_countries         INTEGER DEFAULT 0,
    unique_nodes             INTEGER DEFAULT 0,
    -- Activity
    total_requests           BIGINT DEFAULT 0,
    total_sessions           BIGINT DEFAULT 0,
    avg_session_duration_sec DOUBLE PRECISION DEFAULT 0,
    -- Threats
    total_threat_matches     BIGINT DEFAULT 0,
    threat_categories        TEXT,         -- JSON map
    -- Correlation
    shared_ip_users          INTEGER DEFAULT 0,
    shared_hwid_users        INTEGER DEFAULT 0,
    cluster_ids              TEXT,         -- JSON array
    -- Time
    first_seen               TIMESTAMPTZ,
    last_seen                TIMESTAMPTZ,
    active_days              INTEGER DEFAULT 0,
    typical_hours            TEXT,         -- JSON array
    -- Risk
    risk_score               INTEGER DEFAULT 0,
    risk_factors             TEXT,         -- JSON array
    -- Remnawave mirror
    remna_uuid               TEXT,
    remna_status             TEXT,
    remna_traffic_used       BIGINT DEFAULT 0,
    remna_traffic_limit      BIGINT DEFAULT 0,
    remna_expire_at          TIMESTAMPTZ,
    remna_hwid_devices       INTEGER DEFAULT 0,
    remna_hwid_limit         INTEGER DEFAULT 0,
    -- Metadata
    updated_at               TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS user_sessions (
    id                BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_email        TEXT NOT NULL,
    ip_address        TEXT NOT NULL,
    hwid              TEXT,
    node_id           TEXT,
    started_at        TIMESTAMPTZ DEFAULT NOW(),
    ended_at          TIMESTAMPTZ,
    request_count     BIGINT DEFAULT 0,
    bytes_transferred BIGINT DEFAULT 0
);

-- =============================================================================
-- Remnawave mirror (synced from Remnawave API)
-- =============================================================================

CREATE TABLE IF NOT EXISTS remna_users (
    uuid                    TEXT PRIMARY KEY,
    id                      BIGINT,
    short_uuid              TEXT,
    username                TEXT NOT NULL,
    email                   TEXT,
    status                  TEXT NOT NULL,
    traffic_limit_bytes     BIGINT DEFAULT 0,
    used_traffic_bytes      BIGINT DEFAULT 0,
    lifetime_traffic_bytes  BIGINT DEFAULT 0,
    traffic_limit_strategy  TEXT,
    expire_at               TIMESTAMPTZ,
    online_at               TIMESTAMPTZ,
    first_connected_at      TIMESTAMPTZ,
    hwid_device_limit       INTEGER,
    hwid_device_count       INTEGER DEFAULT 0,
    telegram_id             BIGINT,
    description             TEXT,
    tag                     TEXT,
    created_at              TIMESTAMPTZ,
    updated_at              TIMESTAMPTZ,
    synced_at               TIMESTAMPTZ DEFAULT NOW(),
    real_name               TEXT,
    phone                   TEXT,
    telegram_user           TEXT,
    payment_info            TEXT,
    plan                    TEXT,
    us_id                   TEXT
);

CREATE TABLE IF NOT EXISTS remna_hwid_devices (
    id             BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    hwid           TEXT NOT NULL,
    user_uuid      TEXT NOT NULL,
    username       TEXT,
    platform       TEXT,
    os_version     TEXT,
    device_model   TEXT,
    app_version    TEXT,
    first_seen_at  TIMESTAMPTZ DEFAULT NOW(),
    last_active_at TIMESTAMPTZ,
    synced_at      TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE (hwid, user_uuid)
);

CREATE TABLE IF NOT EXISTS remna_nodes (
    uuid             TEXT PRIMARY KEY,
    name             TEXT NOT NULL,
    address          TEXT,
    port             INTEGER,
    is_connected     INTEGER DEFAULT 0 NOT NULL,
    is_disabled      INTEGER DEFAULT 0 NOT NULL,
    is_traffic_track INTEGER DEFAULT 0 NOT NULL,
    traffic_total    BIGINT DEFAULT 0,
    traffic_used     BIGINT DEFAULT 0,
    users_online     BIGINT DEFAULT 0,
    country_code     TEXT,
    synced_at        TIMESTAMPTZ DEFAULT NOW()
);

-- =============================================================================
-- Online snapshots (1/min cron)
-- =============================================================================

CREATE TABLE IF NOT EXISTS online_snapshots (
    ts           TIMESTAMPTZ PRIMARY KEY,
    total_online BIGINT NOT NULL
);

-- =============================================================================
-- Bridged flows: bridge-node ingress <-> exit-node egress correlation
-- =============================================================================

CREATE TABLE IF NOT EXISTS bridged_flows (
    id             BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_email     TEXT NOT NULL,
    real_client_ip TEXT NOT NULL,
    bridge_node_id TEXT NOT NULL,
    exit_node_id   TEXT NOT NULL,
    destination    TEXT NOT NULL,
    ts             TIMESTAMPTZ NOT NULL,
    created_at     TIMESTAMPTZ DEFAULT NOW()
);

-- =============================================================================
-- AI chat sessions
-- =============================================================================

CREATE TABLE IF NOT EXISTS ai_chat_sessions (
    id           TEXT PRIMARY KEY,
    title        TEXT,
    created_at   TIMESTAMPTZ DEFAULT NOW(),
    updated_at   TIMESTAMPTZ DEFAULT NOW(),
    total_tokens BIGINT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS ai_chat_messages (
    id          BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    session_id  TEXT NOT NULL REFERENCES ai_chat_sessions(id) ON DELETE CASCADE,
    role        TEXT NOT NULL,
    content     TEXT NOT NULL,
    tokens_used BIGINT DEFAULT 0,
    created_at  TIMESTAMPTZ DEFAULT NOW()
);

-- =============================================================================
-- Indexes
-- =============================================================================

-- user_stats
CREATE INDEX IF NOT EXISTS idx_user_stats_node            ON user_stats(node_id);
CREATE INDEX IF NOT EXISTS idx_user_stats_email           ON user_stats(user_email);
CREATE INDEX IF NOT EXISTS idx_user_stats_blacklist       ON user_stats(blacklist_hits DESC);
CREATE INDEX IF NOT EXISTS idx_user_stats_node_lastseen   ON user_stats(node_id, last_seen DESC);
CREATE INDEX IF NOT EXISTS idx_user_stats_requests        ON user_stats(total_requests DESC);

-- blacklist_matches
CREATE INDEX IF NOT EXISTS idx_blacklist_node          ON blacklist_matches(node_id);
CREATE INDEX IF NOT EXISTS idx_blacklist_user          ON blacklist_matches(user_email);
CREATE INDEX IF NOT EXISTS idx_blacklist_time          ON blacklist_matches(timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_blacklist_user_time     ON blacklist_matches(user_email, timestamp DESC);

-- alerts
CREATE INDEX IF NOT EXISTS idx_alerts_sent    ON alerts(sent);
CREATE INDEX IF NOT EXISTS idx_alerts_created ON alerts(created_at);

-- hourly_stats
CREATE INDEX IF NOT EXISTS idx_hourly_stats_hour ON hourly_stats(hour DESC);

-- user_destinations
CREATE INDEX IF NOT EXISTS idx_user_dest_email ON user_destinations(user_email);
CREATE INDEX IF NOT EXISTS idx_user_dest_time  ON user_destinations(last_seen DESC);

-- threat_matches
CREATE INDEX IF NOT EXISTS idx_threat_user ON threat_matches(user_email);
CREATE INDEX IF NOT EXISTS idx_threat_time ON threat_matches(matched_at DESC);
CREATE INDEX IF NOT EXISTS idx_threat_type ON threat_matches(threat_type);
-- Covers the per-(user, type) trim on SaveThreatMatch hot path.
CREATE INDEX IF NOT EXISTS idx_threat_user_type_time
    ON threat_matches(user_email, threat_type, matched_at DESC);

-- user_threat_stats
CREATE INDEX IF NOT EXISTS idx_user_threat_type  ON user_threat_stats(threat_type);
CREATE INDEX IF NOT EXISTS idx_user_threat_count ON user_threat_stats(match_count DESC);

-- threat hourly/daily (leading PK columns already indexed)

-- threat_geo_stats
CREATE INDEX IF NOT EXISTS idx_threat_geo_country ON threat_geo_stats(country_code);

-- user_locations
CREATE INDEX IF NOT EXISTS idx_user_loc_email ON user_locations(user_email);

-- user_ip_history
CREATE INDEX IF NOT EXISTS idx_user_ip_email    ON user_ip_history(user_email);
CREATE INDEX IF NOT EXISTS idx_user_ip_lastseen ON user_ip_history(user_email, last_seen DESC);

-- anomalies (renamed to avoid clash with idx_alerts_created)
CREATE INDEX IF NOT EXISTS idx_anomaly_time ON anomalies(detected_at DESC);
CREATE INDEX IF NOT EXISTS idx_anomaly_user ON anomalies(user_email);
CREATE INDEX IF NOT EXISTS idx_anomaly_type ON anomalies(type);

-- user_risk_profiles
CREATE INDEX IF NOT EXISTS idx_risk_level ON user_risk_profiles(risk_level);
CREATE INDEX IF NOT EXISTS idx_risk_score ON user_risk_profiles(risk_score DESC);

-- dns_domain_stats
CREATE INDEX IF NOT EXISTS idx_dns_domain_hits ON dns_domain_stats(total_hits DESC);
CREATE INDEX IF NOT EXISTS idx_dns_domain_risk ON dns_domain_stats(risk_level);

-- dns hourly/daily (hour/day are PKs; no separate index needed)

-- user_dns_stats
CREATE INDEX IF NOT EXISTS idx_user_dns_blocked ON user_dns_stats(blocked_queries DESC);

-- reports
CREATE INDEX IF NOT EXISTS idx_reports_generated ON reports(generated_at DESC);
CREATE INDEX IF NOT EXISTS idx_reports_type      ON reports(type);

-- ip_user_map / hwid_user_map
CREATE INDEX IF NOT EXISTS idx_ip_user_map_user     ON ip_user_map(user_email);
CREATE INDEX IF NOT EXISTS idx_ip_user_map_lastseen ON ip_user_map(last_seen DESC);
CREATE INDEX IF NOT EXISTS idx_ip_user_map_count    ON ip_user_map(request_count DESC);

CREATE INDEX IF NOT EXISTS idx_hwid_user_map_user  ON hwid_user_map(user_email);
CREATE INDEX IF NOT EXISTS idx_hwid_user_map_count ON hwid_user_map(request_count DESC);

-- user_fingerprints
CREATE INDEX IF NOT EXISTS idx_fingerprint_user ON user_fingerprints(user_email);
CREATE INDEX IF NOT EXISTS idx_fingerprint_ip   ON user_fingerprints(ip_address);
CREATE INDEX IF NOT EXISTS idx_fingerprint_hwid ON user_fingerprints(hwid);

-- user_clusters
CREATE INDEX IF NOT EXISTS idx_cluster_user ON user_clusters(user_email);

-- user_ai_profile
CREATE INDEX IF NOT EXISTS idx_ai_profile_risk   ON user_ai_profile(risk_score DESC);
CREATE INDEX IF NOT EXISTS idx_ai_profile_shared ON user_ai_profile(shared_ip_users DESC, shared_hwid_users DESC);

-- user_sessions
CREATE INDEX IF NOT EXISTS idx_sessions_user ON user_sessions(user_email);
CREATE INDEX IF NOT EXISTS idx_sessions_time ON user_sessions(started_at DESC);

-- remna_users
CREATE INDEX IF NOT EXISTS idx_remna_users_username ON remna_users(username);
CREATE INDEX IF NOT EXISTS idx_remna_users_email    ON remna_users(email);
CREATE INDEX IF NOT EXISTS idx_remna_users_status   ON remna_users(status);
CREATE INDEX IF NOT EXISTS idx_remna_users_online   ON remna_users(online_at DESC);
CREATE INDEX IF NOT EXISTS idx_remna_users_expire   ON remna_users(expire_at);
CREATE INDEX IF NOT EXISTS idx_remna_users_tag      ON remna_users(tag);
CREATE INDEX IF NOT EXISTS idx_remna_users_traffic  ON remna_users(used_traffic_bytes DESC);
CREATE INDEX IF NOT EXISTS idx_remna_users_id       ON remna_users(id);
CREATE INDEX IF NOT EXISTS idx_remna_users_us_id    ON remna_users(us_id);

-- remna_hwid_devices
CREATE INDEX IF NOT EXISTS idx_remna_hwid_hwid   ON remna_hwid_devices(hwid);
CREATE INDEX IF NOT EXISTS idx_remna_hwid_user   ON remna_hwid_devices(user_uuid);
CREATE INDEX IF NOT EXISTS idx_remna_hwid_active ON remna_hwid_devices(last_active_at DESC);

-- remna_nodes
CREATE INDEX IF NOT EXISTS idx_remna_nodes_connected ON remna_nodes(is_connected);
CREATE INDEX IF NOT EXISTS idx_remna_nodes_country   ON remna_nodes(country_code);

-- online_snapshots (ts is PK; no separate index needed)

-- bridged_flows
CREATE INDEX IF NOT EXISTS idx_bridged_flows_user ON bridged_flows(user_email, ts DESC);
CREATE INDEX IF NOT EXISTS idx_bridged_flows_dest ON bridged_flows(destination);
CREATE INDEX IF NOT EXISTS idx_bridged_flows_ip   ON bridged_flows(real_client_ip);
CREATE INDEX IF NOT EXISTS idx_bridged_flows_ts   ON bridged_flows(ts DESC);

-- ai_chat
CREATE INDEX IF NOT EXISTS idx_chat_sessions_updated ON ai_chat_sessions(updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_chat_messages_session ON ai_chat_messages(session_id);
CREATE INDEX IF NOT EXISTS idx_chat_messages_time    ON ai_chat_messages(created_at);

-- =============================================================================
-- Seed rows
-- =============================================================================

INSERT INTO threat_stats_agg (id, total_matches) VALUES (1, 0) ON CONFLICT DO NOTHING;
