// migrate-from-sqlite copies analyzer data from the old SQLite file to the
// new Postgres instance. Invoked once during the cut-over. Stays behind the
// sqlite_legacy build tag so modernc.org/sqlite doesn't get pulled into the
// main binary.

//go:build sqlite_legacy

package main

import (
	"context"
	"database/sql"
	"flag"
	"fmt"
	"log"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
	_ "modernc.org/sqlite"
)

func main() {
	sqlitePath := flag.String("sqlite", "/app/data/analyzer.db", "path to existing SQLite database")
	pgURL := flag.String("postgres", "", "Postgres DSN (required)")
	retentionDays := flag.Int("history-days", 7, "how many days of history to migrate")
	flag.Parse()

	if *pgURL == "" {
		log.Fatal("-postgres required")
	}

	sqliteDB, err := sql.Open("sqlite", "file:"+*sqlitePath+"?mode=ro")
	if err != nil {
		log.Fatalf("open sqlite: %v", err)
	}
	defer sqliteDB.Close()

	ctx := context.Background()
	pg, err := pgxpool.New(ctx, *pgURL)
	if err != nil {
		log.Fatalf("open postgres: %v", err)
	}
	defer pg.Close()

	cutoff := time.Now().UTC().Add(-time.Duration(*retentionDays) * 24 * time.Hour)

	// Full-copy tables — no time filter.
	// Tables with a BIGINT identity PK are listed in identityTables below so
	// their sequence is advanced after the copy.
	for _, t := range []string{
		"remna_users",
		"remna_hwid_devices",
		"remna_nodes",
		"node_stats",
		"user_stats",
		"user_risk_profiles",
		"user_ip_history",
		"ip_user_map",
		"hwid_user_map",
		"user_fingerprints",
		"user_locations",
		"bridged_flows",
		"online_snapshots",
	} {
		migrateFull(ctx, sqliteDB, pg, t)
	}

	// 7-day history tables.
	migrateWithCutoff(ctx, sqliteDB, pg, "hourly_stats", "hour", cutoff)
	migrateWithCutoff(ctx, sqliteDB, pg, "threat_matches", "matched_at", cutoff)
	migrateWithCutoff(ctx, sqliteDB, pg, "blacklist_matches", "timestamp", cutoff)

	// Anomalies: unresolved OR recent (TEXT PK — no identity sequence).
	migrateAnomalies(ctx, sqliteDB, pg)

	// Advance identity sequences so post-migration INSERTs don't collide.
	// These are all tables (migrated or not) that use GENERATED BY DEFAULT AS
	// IDENTITY. We reset every one of them; tables that weren't migrated will
	// just set the sequence to 1 which is harmless since no rows exist.
	identityTables := []struct {
		table  string
		pkCol  string
	}{
		{"user_stats", "id"},
		{"blacklist_matches", "id"},
		{"alerts", "id"},
		{"hourly_stats", "id"},
		{"user_destinations", "id"},
		{"threat_matches", "id"},
		{"user_ip_history", "id"},
		{"user_fingerprints", "id"},
		{"user_sessions", "id"},
		{"remna_hwid_devices", "id"},
		{"bridged_flows", "id"},
		{"ai_chat_messages", "id"},
	}
	for _, t := range identityTables {
		advanceSequence(ctx, pg, t.table, t.pkCol)
	}

	log.Println("migration complete")
}

// migrateFull copies every row from the source table into the Postgres table
// using COPY FROM for throughput.
func migrateFull(ctx context.Context, src *sql.DB, dst *pgxpool.Pool, table string) {
	rows, err := src.QueryContext(ctx, "SELECT * FROM "+table)
	if err != nil {
		log.Printf("%s: source query: %v", table, err)
		return
	}
	defer rows.Close()

	cols, err := rows.Columns()
	if err != nil {
		log.Printf("%s: columns: %v", table, err)
		return
	}

	copyRows := &sqlRowSource{rows: rows, cols: cols}
	tag, err := dst.CopyFrom(ctx, pgx.Identifier{table}, cols, copyRows)
	if err != nil {
		log.Printf("%s: COPY: %v (rows copied=%d)", table, err, tag)
		return
	}
	log.Printf("%s: copied %d rows", table, tag)
}

// migrateWithCutoff copies rows where <timeCol> >= cutoff. SQLite stores
// datetimes as ISO-8601 / RFC3339 strings, so lexical comparison works.
func migrateWithCutoff(ctx context.Context, src *sql.DB, dst *pgxpool.Pool, table, timeCol string, cutoff time.Time) {
	rows, err := src.QueryContext(ctx,
		fmt.Sprintf("SELECT * FROM %s WHERE %s >= ?", table, timeCol),
		cutoff.Format(time.RFC3339))
	if err != nil {
		log.Printf("%s: %v", table, err)
		return
	}
	defer rows.Close()

	cols, err := rows.Columns()
	if err != nil {
		log.Printf("%s: columns: %v", table, err)
		return
	}

	copyRows := &sqlRowSource{rows: rows, cols: cols}
	tag, err := dst.CopyFrom(ctx, pgx.Identifier{table}, cols, copyRows)
	if err != nil {
		log.Printf("%s: %v", table, err)
		return
	}
	log.Printf("%s (>=%s): %d rows", table, cutoff.Format("2006-01-02"), tag)
}

// migrateAnomalies copies unresolved anomalies plus anything detected in the
// last 7 days. The anomalies table uses a TEXT primary key so no sequence
// advancement is needed.
func migrateAnomalies(ctx context.Context, src *sql.DB, dst *pgxpool.Pool) {
	rows, err := src.QueryContext(ctx,
		`SELECT * FROM anomalies WHERE resolved = 0 OR detected_at >= datetime('now','-7 days')`)
	if err != nil {
		log.Printf("anomalies: %v", err)
		return
	}
	defer rows.Close()

	cols, err := rows.Columns()
	if err != nil {
		log.Printf("anomalies: columns: %v", err)
		return
	}

	copyRows := &sqlRowSource{rows: rows, cols: cols}
	tag, err := dst.CopyFrom(ctx, pgx.Identifier{"anomalies"}, cols, copyRows)
	if err != nil {
		log.Printf("anomalies COPY: %v", err)
		return
	}
	log.Printf("anomalies (active+7d): %d rows", tag)
}

// advanceSequence sets the identity sequence for table.pkCol to MAX(pkCol)+1
// so that future INSERTs don't collide with migrated rows. Safe to call even
// when the table is empty (MAX returns NULL → sequence stays at 1).
func advanceSequence(ctx context.Context, pg *pgxpool.Pool, table, pkCol string) {
	query := fmt.Sprintf(`
		SELECT setval(
			pg_get_serial_sequence('%s', '%s'),
			COALESCE(MAX(%s), 0) + 1,
			false
		) FROM %s`, table, pkCol, pkCol, table)

	var val int64
	err := pg.QueryRow(ctx, query).Scan(&val)
	if err != nil {
		log.Printf("advanceSequence %s.%s: %v", table, pkCol, err)
		return
	}
	log.Printf("sequence %s.%s advanced to %d", table, pkCol, val)
}

// sqlRowSource adapts *sql.Rows to pgx.CopyFromSource.
type sqlRowSource struct {
	rows *sql.Rows
	cols []string
	vals []any
	err  error
}

func (s *sqlRowSource) Next() bool {
	if !s.rows.Next() {
		return false
	}
	s.vals = make([]any, len(s.cols))
	ptrs := make([]any, len(s.cols))
	for i := range s.vals {
		ptrs[i] = &s.vals[i]
	}
	if err := s.rows.Scan(ptrs...); err != nil {
		s.err = err
		return false
	}
	return true
}

func (s *sqlRowSource) Values() ([]any, error) { return s.vals, s.err }
func (s *sqlRowSource) Err() error             { return s.err }
